### PR TITLE
Provide a debug endpoint

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundleservice/19/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundleservice/20/
Test PASSed.

**Comment by makyo** [comment]
# QA
- `make run`
- Visit /debug/info and ensure that the commit revnos show up

**Review by jrwren — APPROVED** [review]

**Review by hatched — APPROVED** [review]
Cool approach to the versioning. Thanks @makyo

**Comment by makyo** [comment]
thanks all :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundleservice-merge

**Pull request merged**
